//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtFeedback4
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseType
    {
        public CaseType()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int CaseTypeId { get; set; }
        public string CaseType1 { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
