//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtFeedback4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public System.DateTime FeedbackDate { get; set; }
        public string FeedbackFull { get; set; }
        public int CourtId { get; set; }
        public int CountryId { get; set; }
        public int CaseTypeId { get; set; }
        public string Attachment { get; set; }
        public Nullable<int> Approved { get; set; }
        public string FeedbackTitle { get; set; }
    
        public virtual CaseType CaseType { get; set; }
        public virtual Country Country { get; set; }
        public virtual Court Court { get; set; }
    }
}
