//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtFeedback4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourtFeedbackEntities4 : DbContext
    {
        public CourtFeedbackEntities4()
            : base("name=CourtFeedbackEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<CaseType> CaseTypes { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Court> Courts { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<UserFeedback> UserFeedbacks { get; set; }
    }
}
