//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtFeedback4
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFeedback
    {
        public int UserFeedbackId { get; set; }
        public string UserEmail { get; set; }
        public string FeedbackTitle { get; set; }
        public string FeedbackDesc { get; set; }
        public string UFCourt { get; set; }
        public string UFCountry { get; set; }
        public string UFCaseType { get; set; }
        public string UFBlobContainer { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
